name: wayii
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  get: 4.6.5
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  path_provider: ^2.0.15
  dots_indicator: ^3.0.0
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.7
  curved_navigation_bar: ^1.0.3
  simple_animations: ^5.0.1
  shimmer: ^3.0.0
  collection: ^1.17.0
  badges: ^3.1.2
  shared_preferences: ^2.2.2
  like_button: ^2.0.5
  flutter_otp_text_field: ^1.1.1
  flutter_staggered_animations: ^1.1.1
  http: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Futura
      fonts:
        - asset: fonts/FuturaPTLight.otf
          style: normal

flutter_launcher_icons:
  android: true
  image_path_android: assets/images/logo.png
  image_path_ios: assets/images/logo.png
  ios: true